// Generated by SolidPython 1.1.3 on 2022-04-22 13:44:22


difference() {
	sphere(size = 100);
	cube(size = 150);
	cylinder(r = 50);
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from solid import *
from solid.utils import *
import viewscad


d = cube(5) + right(5)(sphere(5)) - cylinder(r=2, h=6)

a = difference()(
    cube(100),  # Note the comma between each element!
    sphere(150),
    cylinder(50)
)
scad_render_to_file(a,'test_a.scad')
renderer = viewscad.Renderer(openscad_exec='./test_a.scad')
scad_render_to_file(d,'test_d.scad')
renderer = viewscad.Renderer(openscad_exec='./test_d.scad')
 
 
************************************************/
